# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

# Workaround for Docker for Windows in Git Bash.
# docker()
# {
# export MSYS_NO_PATHCONV=1
# ("$DOCKER_HOME/docker.exe" “$@”)
# export MSYS_NO_PATHCONV=0
# }